apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsushin.fullname" . }}-frontend
  namespace: {{ include "tsushin.namespace" . }}
  labels:
    {{- include "tsushin.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tsushin.frontend.selectorLabels" . | nindent 4 }}
