{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tsushin.fullname" . }}-data
  namespace: {{ include "tsushin.namespace" . }}
  labels:
    {{- include "tsushin.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
