{{- if not .Values.secrets.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsushin.secretName" . }}
  namespace: {{ include "tsushin.namespace" . }}
  labels:
    {{- include "tsushin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
